### ISSUE TITLE
American vs UK spelling - Yelp Dataset

### ISSUE THREAD

**Issue by DeNeutoy** [jkkummerfeld/text2sql-data#26]
The actual yelp database uses American spelling of NEIGHBORHOOD, but the schema and data use NEIGHBOURHOOD.

These should probably be canonicalised (or is that canonicalized?!).

**Comment by jkkummerfeld** [comment]
Good catch! Now fixed by a678e1be5efdc55d5c5f760e9328a8a036dc1b47
