### ISSUE TITLE
Hyperparameters for small datsets

### ISSUE THREAD

**Issue by DeNeutoy** [jkkummerfeld/text2sql-data#29]
Hi Jonathan - just wondering how the hyperparameters for the slot filling baseline were chosen? The code doesn't do any early stopping based on a development split - were these based off some intuition about the dataset's relative sizes compared to the datasets which do have train/dev/test splits?

Thanks!

**Comment by jkkummerfeld** [comment]
That's right. There is a good chance that there is scope for improvement with some optimisation, but doing that without overfitting seems tricky.
