### ISSUE TITLE
Any canonicalization for quotes?

### ISSUE THREAD

**Issue by todpole3** [jkkummerfeld/text2sql-data#32]
It looks like the "canonicaliser.py" file does not contain a procedure for normalizing quotes around values in SQL such as \"EMNLP\". For example, some quotes are removable and sometimes single quotes and double quotes are exchangeable (I'm not entirely sure that this is true).

Hence I wonder if the dataset has any canonicalization regarding this?

**Comment by jkkummerfeld** [comment]
The `standardise_blank_spaces` function does convert single quotes to double quotes (see https://github.com/jkkummerfeld/text2sql-data/blob/master/tools/canonicaliser.py#L192 ), which I realise is a bit counter-intuitive given the function name...

Knowing when quotes are removable seems like a harder problem. I'm going to close this issue for now, but please reopen it if you have a suggestion on that!

**Comment by todpole3** [comment]
That makes sense. Thanks.
