### ISSUE TITLE
Allen NLP Text2SQL

### ISSUE THREAD

**Issue by Sharathmk99** [jkkummerfeld/text2sql-data#39]
Hi,
Can i use the data of ATIS data set from here to train AllenNLP Text2SQL model?

Thank you!

**Comment by jkkummerfeld** [comment]
Hi,
In theory yes, but it might be difficult. My understanding of their text2sql model (as described in their ACL paper) is that it uses the schema of the database, which is quite complex in the case of ATIS. I would suggest contacting Matt Gardner or Mark Neumann, who have previously worked on using our data in AllenNLP.

Thanks!

Jonathan
