### ISSUE TITLE
Spacing error(?) in geography.json

### ISSUE THREAD

**Issue by whwang299** [jkkummerfeld/text2sql-data#41]
Hi @jkkummerfeld 

I think "(SELECT" in the code below should change into "( SELECT" for the consistency. 
https://github.com/jkkummerfeld/text2sql-data/blob/7aaae5bfcce37a54d1d713cabb27ee60dc9ba422/data/geography.json#L7666

Thanks for the great work.

Wonseok

**Comment by whwang299** [comment]
Also, 
`TMP` in following code should change into `DERIVED_TABLE`  with additional `AS`?
https://github.com/jkkummerfeld/text2sql-data/blob/7aaae5bfcce37a54d1d713cabb27ee60dc9ba422/data/geography.json#L8004

**Comment by jkkummerfeld** [comment]
Thanks for raising these! I won't be able to get to this until the weekend, but if you draft a Pull Request before then I'd be happy to review it.

**Comment by whwang299** [comment]
I have made pull request (https://github.com/jkkummerfeld/text2sql-data/pull/42). Please review :).

Thanks!

**Comment by jkkummerfeld** [comment]
Thanks! Merged. I've also pushed a general update to master with other improvements that were waiting in our data development branch.
