### ISSUE TITLE
Naming error (?) in restaurants.json

### ISSUE THREAD

**Issue by whwang299** [jkkummerfeld/text2sql-data#44]
Hi @jkkummerfeld 

There seem to be small naming inconsistency between `restaurants.json` and other files.

In `restaurants.json`, `RESTAUANT` table (when it is represented as RESTAURANTalias0 or RESTAURANTalias01) has `ID`

https://github.com/jkkummerfeld/text2sql-data/blob/ea9f7a09db24f02298c513d87953d5efc93e0d8a/data/restaurants.json#L33

On the other hand, `restaurants-field.txt` has `RESTAURANT_ID` instead of `ID`.

https://github.com/jkkummerfeld/text2sql-data/blob/ea9f7a09db24f02298c513d87953d5efc93e0d8a/data/restaurants-fields.txt#L1

Same goes for `restaurants-schema.csv`

Thanks!

Wonseok

**Comment by jkkummerfeld** [comment]
Fixed by the PR noted above. Thanks for pointing this out!
