### ISSUE TITLE
This is more of a question than issue.

### ISSUE THREAD

**Issue by aerinkim** [jkkummerfeld/text2sql-data#47]
Hi, thank you for releasing the dataset.

What does 'query-split' and 'question-split' mean, in the dataset?
For example, in the last entry of restaurant dataset, 

```
where can i find a name0 in city_name0 ?
where is name0 in city_name0 ?
where is a name0 in city_name0 ?
```

are duplicated 3 times but their `question-split` are different.
Any pointer would be appreciated. (Can't find it on the paper.)

**Comment by jkkummerfeld** [comment]
Hi,
Thanks for your interest! The question split was formed by taking the set of (question, SQL query) pairs and randomly dividing it. The query split was formed by taking the set of queries and randomly dividing them (that means all questions for a given query are in the same set). See figure 1 in the paper for an example to get some intuition and for full details see the start of section 5.

Jonathan

**Comment by aerinkim** [comment]
Thank you so much, now it makes sense.
