### ISSUE TITLE
location.restaurant_id should be foreign key in "Restaurants"?

### ISSUE THREAD

**Issue by rizar** [jkkummerfeld/text2sql-data#50]
I am looking at the restaurants database. It contains tables `Restaurants` and `Location`. As far as I can understand from eyeballing the db content, `Location.restaurant_id` is referring to `Restaurants.id`, i.e. table `Location` contains addresses of the restaurants in table `Restaurants`. But in the database creation code `Location.restaurant_id` is made a primary key, not a foreign key:

https://github.com/jkkummerfeld/text2sql-data/blob/master/tools/create_restaurant_database.py#L32

What would be the right thing to do here?

**Comment by jkkummerfeld** [comment]
You're right - that's an error, I'll update that code (note that this is not actually code we used in our experiments, it was contributed to the repository later).

**Comment by jkkummerfeld** [comment]
Done

**Comment by rizar** [comment]
Great, thanks a lot for the quick response!
