### ISSUE TITLE
Wrong output of Geography using json_to_flat.py

### ISSUE THREAD

**Issue by PosoSAgapo** [jkkummerfeld/text2sql-data#52]
Hi, I use json_to_flat.py to produce data for query split of Geography ,but it seems some data are missing in its SQL query. In the last line of the test data, there is only human query and the SQL programm is missing.

**Comment by jkkummerfeld** [comment]
I'm not seeing this issue. Here is what I ran:

```
echo data/geography.json| python tools/json_to_flat.py debug
grep -v 'SELECT' debug.*
```

I also manually checked the output file and could see the SQL queries.

Could you share extra details about how you were running the code?

**Comment by PosoSAgapo** [comment]
I just use python json_to_flat.py -query_spli Geography, then I input the address of Geography, the output misses some SQL queries, I don't know why, but the code seems to work normally now. Thank you for your reply!

**Comment by jkkummerfeld** [comment]
Glad it's working now!
