### ISSUE TITLE
Downloading the database

### ISSUE THREAD

**Issue by awasthiabhijeet** [jkkummerfeld/text2sql-data#53]
Hi @jkkummerfeld,

Thanks for open-sourcing the code and datasets.

The google drive links for Academic (MAS), IMDB, Yelp, and Scholar databases are not publicly accessible.
Could you please share them with my email id  (174050004@iitb.ac.in) ?

Thanks :)

**Comment by jkkummerfeld** [comment]
Hi,

Unfortunately, I can't help much as I'm not the owner of those resources. For the first three, contact the SQLizer authors (https://dl.acm.org/doi/10.1145/3133887). For Scholar, contact the authors of [this paper](https://aclanthology.org/P17-1089.pdf).

For what it's worth, I don't believe I needed to request access. I did need to be logged in to a Google account, but that's it.

Jonathan

**Comment by awasthiabhijeet** [comment]
Thank you for the response.
As of 04-09-2022, both the files seem to have restricted access. I'm unable to download them while being logged in to a Google account. 
Will update this space if I find sources from where these databases can be downloaded more easily.

**Comment by jkkummerfeld** [comment]
I've reached out to the authors of these two papers to ask if I can upload the databases somewhere else for people to access. I will follow up here once I receive a response.

**Comment by jkkummerfeld** [comment]
Hi @awasthiabhijeet and @dsying2022, I've just pushed a commit that provides an alternative URL to download these datasets (created with permission from the original paper authors).

If you have any issues accessing the data, please reopen this issue.

**Comment by awasthiabhijeet** [comment]
Thanks, @jkkummerfeld. This is very helpful!

**Comment by dsying2022** [comment]
> Hi @awasthiabhijeet and @dsying2022, I've just pushed a commit that provides an alternative URL to download these datasets (created with permission from the original paper authors).
> 
> If you have any issues accessing the data, please reopen this issue.

thank you so much！

**Comment by awasthiabhijeet** [comment]
Hi @jkkummerfeld ,

The sharepoint link to download databases seems to have expired.
It would be great if you can update it with a new link.

I currently get the following error: 
![image](https://github.com/jkkummerfeld/text2sql-data/assets/10473221/59e44d21-5e2f-4af2-888a-314a02bb442f)

Thanks,

**Comment by jkkummerfeld** [comment]
Thanks for flagging that. I've made it accessible again. Unfortunately, I can only set an expiry that is 6 months out.

**Comment by awasthiabhijeet** [comment]
Thank you @jkkummerfeld.
The link for Scholar data works fine now. 

However, the [link](https://unisyd-my.sharepoint.com/:u:/g/personal/jonathan_kummerfeld_sydney_edu_au/EZKSPtcxPW9PvodZ-DzYn6YB1bsbREHh2Q5APcqWLOnMeQ?e=Hx0CiU) for Academic / IMDB / Yelp data is still inaccessible. Could you please update it as well? Thanks :)

**Comment by jkkummerfeld** [comment]
Fixed
