### ISSUE TITLE
Unable to find the sequence-to-sequence Baseline models

### ISSUE THREAD

**Issue by kedartatwawadi** [jkkummerfeld/text2sql-data#6]
Hello! 
Thanks for the nice work! Can you please provide the sequence-to-sequence baseline models which you experimented with in the paper? I was unable to locate them in the [sequence-to-sequence](https://github.com/jkkummerfeld/text2sql-data/tree/master/systems/sequence-to-sequence) folder

**Comment by jkkummerfeld** [comment]
Hi,
Thanks for your interest! As noted on that page, that code release is still being prepared. I'm not sure exactly when we'll have it out, but I will respond here when we do.

Jonathan

**Comment by kedartatwawadi** [comment]
Cool! thanks a lot :)

**Comment by cfdollak** [comment]
Seq2seq code is now available in master.

**Comment by kedartatwawadi** [comment]
Thanks!

**Comment by todpole3** [comment]
Looks like the model implementations `text2sql-data/systems/sequence-to-sequence/seq2seq/models` were missing and I failed to execute `./experiment.sh` since it is looking for the class `InputAttentionCopyingSeq2Seq`. 

Would you please complete the repo with these files? Thanks.

**Comment by jkkummerfeld** [comment]
Just a quick follow up here - we're looking into this and will make further updates in the new issue. Thanks!
